sqldemo:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: 'ODBC Driver 18 for SQL Server' # (The ODBC Driver installed on your system)
      server: sql-adventureworks-source.database.windows.net
      database: sql-jaffle-shop-source
      schema: dbt_dev
      authentication: CLI